version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: npm run start
    env_file: .env
    expose:
      - '4000'
    restart: unless-stopped
    volumes:
      - 'static_volume:/app/frontend/build'
  frontend:
     build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - SUBDIRECTORY=${SUBDIRECTORY}
     env_file: .env
     volumes:
        - 'static_volume:/app/frontend/build'
  nginx:
    build: ./nginx
    depends_on:
      - backend
    env_file: .env
    ports:
      - '80:80'
    restart: unless-stopped

volumes:
  static_volume:
